function DATA=TS150M_read 

D=load('TS150M.DAT'); len=length(D);
DATA.SDtime    = datenum(1989,4,7,22,0,0)+(0:(len-1))*1/1440;
DATA.temp      = squeeze(D(:,1));
DATA.cond      = squeeze(D(:,2));
DATA.sal       = squeeze(D(:,3));

DATA.depth=150;
DATA.hdr=['MicroCat sensor S/N 40 was deployed at CEAREX O Camp with first record';...
          'at 22:00, 07-April-1989 UTC, recording every 1 minute, at a nominal   ';...
          'depth of 150 m.                                                       ';...
          '                                                                      ';...
          'File: TS150M.dat                                                      ';...
          '                                                                      ';...
          'Contains 10 header lines, followed by triplets of Temp (C),           ';... 
          'Conductivity (mmho/cm), Salinity (%)                                  ';...
          '                                                                      ';...
          'Matlab function TS150M_read.m reads these data into a structure       ';...
          'DATA, with time in Matlab "datenum" form.                             '];
return
